### ISSUE TITLE
Logo se zobrazuje špatně při portrait layout (mobily, tablety)

### ISSUE THREAD

**Issue by hnykda** [hnykda/ea-cr#1]
![image](https://cloud.githubusercontent.com/assets/2741256/17788777/86d0b0de-658f-11e6-9c1f-c2bb5c9abb2a.png)

![image](https://cloud.githubusercontent.com/assets/2741256/17788790/97897c26-658f-11e6-950b-6f15453365ad.png)

**Comment by nadvornix** [comment]
Jsem domluven s Honzou Rudolfem že si ve středu 2016/8/26 sedneme a opravíme tuhle a pár dalších chyb v vzhledu.

**Comment by hnykda** [comment]
:+1:

**Comment by nadvornix** [comment]
Hotovo.
