### ISSUE TITLE
Rebrandovat na nové logo EA

### ISSUE THREAD

**Issue by MichalPokorny** [hnykda/ea-cr#2]
Z červené žárovky na modrou. Abychom byli konzistentní s celosvětovým hnutím.

**Comment by nadvornix** [comment]
Nuda. Nelíbí se mi a zdaleka nejsme jediný používající červenou žárovku: https://www.google.cz/search?q=effective+altruism&safe=active&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi9ivehz9HOAhVBDMAKHemVBiEQ_AUICCgB&biw=1366&bih=667
